# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"properties": "01_Tasks.ipynb",
         "defaults": "01_Tasks.ipynb",
         "Task": "01_Tasks.ipynb",
         "t": "01_Tasks.ipynb",
         "task_scheduler": "01_Tasks.ipynb",
         "multi_input": "questions.ipynb",
         "clear_screen": "questions.ipynb",
         "enumerator": "questions.ipynb",
         "essentials": "questions.ipynb",
         "work": "questions.ipynb",
         "a": "questions.ipynb",
         "selections": "questions.ipynb",
         "distractions": "questions.ipynb"}

modules = ["core.py",
           "tasks.py",
           "tests.py",
           "questions.py"]

doc_url = "https://Prabhanshu.github.io/Journal/"

git_url = "https://github.com/Prabhanshu/Journal/tree/master/"

def custom_doc_links(name): return None
