# AUTOGENERATED! DO NOT EDIT! File to edit: questions.ipynb (unless otherwise specified).

__all__ = ['multi_input', 'clear_screen', 'enumerator', 'essentials', 'work', 'a', 'selections', 'distractions']

# Cell
import sys
from os import system, name

# Cell
def multi_input():
    try:
        while True:
            data=input()
            if not data: break
            yield data
    except KeyboardInterrupt:
        return

#use list(multi_input)

def clear_screen():

    # for windows
    if name == 'nt':
        _ = system('cls')

    # for mac and linux(here, os.name is 'posix')
    else:
        _ = system('clear')

def enumerator(l: 'list of str'):
    for index, item in enumerate(l):
        print(f'[{index}] {item.capitalize()}')


# Cell
def essentials():
    #introduction
    print(
        """
    Fill this up to hopeless fuck !!
    Take care of the following instructions, don't screw this up !
    Time in 24hr format. Eg: '1500' for 03:00 PM
    Duration in <Number><identifier>. Eg: '35m', '5h', '4d'
        """
         )

    # Q 1 Sleep
    slpt_at = input("When did you sleep ?\n")
    woke_at = input("When did you wake up ?\n")

    # Q 2 Food
    print("""When did you take your meals and for how long ?
    Include the timepass you did after eating.
    Eg:
    0730
    35m
    1600
    1h
    """)
    meals = list(multi_input())

    # Q 3 Mind
    print("""If and when did you meditate and for how long ?
    Press Enter if you didn't meditate. You can add an entry
    if you are going to meditate right now, but add it only
    after the session is over.
    Eg:
    0300
    10m
    """)
    mditate = list(multi_input())
    # add if required: mditate.append(input("On a scale of 1-10 . . .  \n"))
    mditate.append(input("Enter any additional notes\n"))

    # Q 4 Body
    print("""If and when did you exercise and for how long ?
    Press Enter if you didn't.
    Also enter the total number of reps for legs, core and upper respectively.
    Eg:
    0300
    10m
    0
    0
    2
    """)
    exrcise = list(multi_input())
    exrcise.append(input("Enter any additional notes\n"))

    clear_screen()
    print('\nWell this completes the essentials.')
    print('Now lets get to the questions Work\n\n')

    return slpt_at, woke_at, meals, mditate, exrcise

# Cell
clear_screen()
print('\nWell this completes the essentials.')
print('Now lets get to the questions about Deep Work\n\n')

# Cell
def work():
    print("Lets get to tasks")
    print("Following is the list of distractions")
    enumerator(distractions)
    print("Do you want to take on any of them today as tasks?")
    print("\nPress enter if none.\n")
    task_list = [distractions[index] for index in
                  [int(i) for i in multi_input()]]
    print('Any other tasks you would like to add?')
    task_list += list(multi_input())


# Cell
# print("Yesterday following were the tasks you took on to complete")
# print(*tasks, sep='\n')
# # print('\n'.join(tasks))     can also be used


# Cell
a = list(multi_input())


# Cell
selections = list(multi_input())

# Cell
distractions = ['uasnuh','onk','aonusnuh']

# Cell
