# AUTOGENERATED! DO NOT EDIT! File to edit: 01_Tasks.ipynb (unless otherwise specified).

__all__ = ['properties', 'defaults', 'Task', 't', 'task_scheduler']

# Cell
from collections import namedtuple
properties = ['task',
              'Estd_Time',
              'Strt_Date',
              'Time_Takn',
              'Comp_Date',
              'Satsfactn'
             ]
defaults = ['?']*len(properties-1)
Task = namedtuple('Task', properties, defaults=defaults)

# Cell
t = Task(45,10);

# Cell
def task_scheduler(x: 'list of strings of tasks'):
