# AUTOGENERATED! DO NOT EDIT! File to edit: 01_Tasks.ipynb (unless otherwise specified).

__all__ = ['properties', 'defaults', 'Task', 't', 'str2timeDelta', 'args_map', 'task_scheduler']

# Cell
from collections import namedtuple
from datetime import datetime, date, time, timedelta
import re
properties = ['task',
              'Estd_Time',
              'Strt_Date',
              'Time_Takn',
              'Comp_Date',
              'Satsfactn'
             ]
defaults = ['?']*(len(properties)-1)
Task = namedtuple('Task', properties, defaults=defaults)

# Cell
t = Task(45,10);

# Cell
args_map = {'d':'days',
             'h':'hours',
             'w':'weeks',
             'm':'minutes'}

def str2timeDelta(string):

    pattern = re.compile(r"""
    (\d+\.*\d*) #Any real numbers >> Digit decimal digit(optional)
    \s? #To handle space
    ([hmsdw][o]?)  # any of h, m... o is to diff b/w m[in] and m[onth]
    """, re.VERBOSE)
    args_as_tuples_in_list = re.findall(pattern, string)
    args = {args_map.get(arg_tuple[1]) : float(arg_tuple[0])
                        for arg_tuple in args_as_tuples_in_list}
    return timedelta(**args)

# Cell
def task_scheduler(x: 'list of strings of tasks'):
   # Asks the date when this has to be done
    return scheduled_task