# AUTOGENERATED! DO NOT EDIT! File to edit: 03_tests.ipynb (unless otherwise specified).

__all__ = ['test_date']

# Cell
from .tasks_new import *
from .questions import *

# Cell
import unittest

# Cell
from datetime import timedelta
class test_date(unittest.TestCase):
    def test_d(self):
        t1 = str2timeDelta('3m')
        t = timedelta(seconds=180)
        self.assertEqual(t1,t)

# Cell
if __name__ == '__main__':
    unittest.main(argv=['first-arg-is-ignored'], exit=False)